# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Checkin

on:
  push:
    branches: 
      - master
      - feature/*
      - fix/*
      - refactor/*
      - chore/*
      - release/*
      - dev/*
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        pylint \
          train.py train_test.py dqn_agent.py entrypoint.py \
          replay_buffer.py utils.py visualizer.py
    - name: Test
      run: |
        python -m unittest \
          train_test.TestTrain.test_sanity_check \
          play_test.TestPlay.test_sanity_check
